# Generated by Django 5.0.6 on 2024-07-10 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("password", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generate",
            name="leaked",
        ),
        migrations.AddField(
            model_name="generate",
            name="number",
            field=models.IntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(4),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="generate",
            name="special",
            field=models.BooleanField(default=True),
        ),
    ]
