# Generated by Django 5.0.6 on 2024-07-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("password", "0002_remove_generate_leaked_generate_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generate",
            name="number",
        ),
        migrations.AddField(
            model_name="generate",
            name="mdp",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
