# Generated by Django 5.0.6 on 2024-07-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("password", "0003_remove_generate_number_generate_mdp"),
    ]

    operations = [
        migrations.AddField(
            model_name="generate",
            name="novalidate",
            field=models.BooleanField(default=True),
        ),
    ]
