# Generated by Django 5.0.6 on 2024-07-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("password", "0004_generate_novalidate"),
    ]

    operations = [
        migrations.AddField(
            model_name="generate",
            name="scale",
            field=models.IntegerField(default=8),
        ),
    ]
