# Generated by Django 5.0.6 on 2024-07-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("password", "0005_generate_scale"),
    ]

    operations = [
        migrations.AddField(
            model_name="generate",
            name="viability",
            field=models.CharField(
                choices=[
                    ("FA", "Faible"),
                    ("PE", "Personel"),
                    ("NO", "Normal"),
                    ("AD", "Admin"),
                    ("PA", "Passphrase"),
                ],
                default="FA",
                max_length=20,
            ),
        ),
    ]
