# Generated by Django 5.0.6 on 2024-07-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("password", "0006_generate_viability"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generate",
            name="novalidate",
        ),
    ]
