# Generated by Django 5.0.6 on 2024-07-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("password", "0007_remove_generate_novalidate"),
    ]

    operations = [
        migrations.AddField(
            model_name="generate",
            name="simple",
            field=models.BooleanField(default=False),
        ),
    ]
