# Generated by Django 5.0.6 on 2024-07-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("password", "0008_generate_simple"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pwnd", models.TextField()),
            ],
        ),
    ]
