# Generated by Django 5.0.6 on 2024-07-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("password", "0009_dictionary"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Dictionary",
            new_name="Pwned",
        ),
        migrations.RenameField(
            model_name="pwned",
            old_name="pwnd",
            new_name="pwned",
        ),
    ]
