# Generated by Django 5.0.6 on 2024-07-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("password", "0010_rename_dictionary_pwned_rename_pwnd_pwned_pwned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generate",
            name="special",
            field=models.BooleanField(default=True, verbose_name="hola"),
        ),
    ]
