# Generated by Django 5.0.6 on 2024-07-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("password", "0011_alter_generate_special"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pwned",
        ),
        migrations.AlterField(
            model_name="generate",
            name="simple",
            field=models.BooleanField(
                default=False, verbose_name="Mot de Passe Simple à retenir"
            ),
        ),
        migrations.AlterField(
            model_name="generate",
            name="special",
            field=models.BooleanField(default=True, verbose_name="Caractères spéciaux"),
        ),
    ]
