# Generated by Django 4.2.14 on 2024-07-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("password", "0012_delete_pwned_alter_generate_simple_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generate",
            name="password_check",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="generate",
            name="simple",
            field=models.BooleanField(
                default=False, verbose_name="Mot de Passe Simple à retenir "
            ),
        ),
        migrations.AlterField(
            model_name="generate",
            name="special",
            field=models.BooleanField(
                default=True, verbose_name="Caractères spéciaux "
            ),
        ),
    ]
