# Generated by Django 4.2.14 on 2024-07-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("password", "0013_generate_password_check_alter_generate_simple_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generate",
            name="password",
            field=models.CharField(default=float("inf"), max_length=128),
            preserve_default=False,
        ),
    ]
