# Generated by Django 4.2.14 on 2024-07-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("password", "0014_generate_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generate",
            name="password_check",
        ),
        migrations.AlterField(
            model_name="generate",
            name="password",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
