# Generated by Django 4.2.14 on 2024-07-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("password", "0015_remove_generate_password_check_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generate",
            name="passphrase",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="generate",
            name="scale",
            field=models.IntegerField(default=8, null=True),
        ),
    ]
