# Generated by Django 4.2.14 on 2024-07-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("password", "0016_generate_passphrase_alter_generate_scale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generate",
            name="viability",
        ),
    ]
