# Generated by Django 4.2.14 on 2024-07-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("password", "0017_remove_generate_viability"),
    ]

    operations = [
        migrations.AddField(
            model_name="generate",
            name="passphrase_created",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
