# Generated by Django 4.2.14 on 2024-07-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("password", "0018_generate_passphrase_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="generate",
            name="dico_scale",
            field=models.IntegerField(default=4, null=True),
        ),
    ]
