# Generated by Django 4.2.14 on 2024-07-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("password", "0019_generate_dico_scale"),
    ]

    operations = [
        migrations.AddField(
            model_name="generate",
            name="passmot",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
