# Generated by Django 4.2.14 on 2024-07-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("password", "0020_generate_passmot"),
    ]

    operations = [
        migrations.AddField(
            model_name="generate",
            name="separator",
            field=models.CharField(default="/", max_length=3),
        ),
    ]
