# Generated by Django 4.2.14 on 2024-07-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0021_generate_separator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generate',
            name='dico_scale',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
        migrations.AlterField(
            model_name='generate',
            name='mdp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generate',
            name='passmot',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='generate',
            name='passphrase',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generate',
            name='passphrase_created',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='generate',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='generate',
            name='scale',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
    ]
