# Generated by Django 4.2.14 on 2024-07-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0022_alter_generate_dico_scale_alter_generate_mdp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generate',
            name='passmot',
        ),
        migrations.RemoveField(
            model_name='generate',
            name='separator',
        ),
    ]
