# Generated by Django 4.2.14 on 2024-07-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0023_remove_generate_passmot_remove_generate_separator'),
    ]

    operations = [
        migrations.AddField(
            model_name='generate',
            name='passmot',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='generate',
            name='separator',
            field=models.CharField(default='/', max_length=3),
        ),
    ]
